export const VALIDATION_LIMITS = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 50,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 64,
  OTP_CODE_LENGTH: 6,
} as const;

export const NAME_MIN_LENGTH = VALIDATION_LIMITS.NAME_MIN_LENGTH;
export const NAME_MAX_LENGTH = VALIDATION_LIMITS.NAME_MAX_LENGTH;
export const PASSWORD_MIN_LENGTH = VALIDATION_LIMITS.PASSWORD_MIN_LENGTH;
export const PASSWORD_MAX_LENGTH = VALIDATION_LIMITS.PASSWORD_MAX_LENGTH;
export const OTP_CODE_LENGTH = VALIDATION_LIMITS.OTP_CODE_LENGTH;
